### ISSUE TITLE
End to End cryption

### ISSUE THREAD

**Issue by Tom-Hartmann** [powercord-community/suggestions#451] opened 2021-05-19 11:04 UTC
### Description

Encrypts your messages so that no one other than the person with the "key" can read them. For end to end encryption.

### More info
https://github.com/leogx9r/DiscordCrypt
Was made for betterdiscord.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-05-19 11:54
Duplicate of #17

**Closed as completed by cyyynthia** 2021-05-19 11:54 UTC
Labels: declined: duplicate
