### ISSUE TITLE
PCContextMenu

### ISSUE THREAD

**Issue by Iucii** [powercord-community/suggestions#176] opened 2020-09-03 21:48 UTC
### Description
Like bdcontextmenu but for powercord

### More info
pretty self explanatory

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment] 2020-09-03 22:31
Duplicate of #132 

This is on the roadmap for Powercord Core, see the comment I made there

**Closed by Bowser65** 2020-09-03 22:31 UTC
Labels: pending review
