### ISSUE TITLE
Nitro/Custom 'emotes' (or port of EmoteReplacer)

### ISSUE THREAD

**Issue by Ghost-Fysche** [powercord-community/suggestions#433] opened 2021-05-09 05:49 UTC
### Description
Better Discord already has _two_ separate plugins that perform this feature, however, the one I like doesn't run all that well with BDcompat. While Freemoji _does_ work, it only supports original size, and 64px (and if you are smart 32px), but not 42px which is the default resolution of an emote only post.

### More info
https://github.com/Yentis/betterdiscord-emotereplacer (their github)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-05-09 14:11
Duplicate of #186. We don't accept plugins giving "free nitro" as per our guidelines.

**Closed as completed by cyyynthia** 2021-05-09 14:11 UTC
Labels: declined: guidelines, declined: duplicate
