### ISSUE TITLE
QueueMessages

### ISSUE THREAD

**Issue by CandyIsaChad** [powercord-community/suggestions#583] opened 2021-09-01 02:48 UTC
### Description
 Queue messages on channels that have slowmode on them, so people don't have to wait for the cooldown to end just to send a single message.

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment] 2021-09-01 08:12
Dupe of #277

**Closed as completed** 2021-09-01 11:19 UTC
Labels: declined: duplicate
