### ISSUE TITLE
Guild Invite Log

### ISSUE THREAD

**Issue by MulverineX** [powercord-community/suggestions#580] opened 2021-08-25 04:24 UTC
### Description
A log of all servers you've joined and what invite code you used.

### More info
Potential Features:
 - Context menu/right-click option on links in chat to manually add them to your list
 - Collapsed list of servers in settings with logged invites with buttons to check the link, copy the link, and remove it (also a button to remove a server from the list entirely)
 - Setting to automatically remove invites when the manual check finds a dead link
 - Setting to clear the log
 - Setting to hide servers from the displayed list that you are already in
 - Command for accessing a specific logged server's invites (via ID or name search) that provides the same options as the settings list + a button to insert it into the text input. Search & id will override the above setting.
 - Command for manually adding an invite link

Details: 

Stores invites in settings file & in local storage (the latter so other plugins can integrate with the list). Caches current server id, logo (base64 image, not link), name, and invites.

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment] 2021-08-25 07:46
Dupe of #268 but this has more details.

**Comment by MulverineX** [comment] 2021-08-25 07:53
@DracoClaw woops! Could you please edit in my details? I'll close this issue.

**Closed as completed** 2021-08-29 21:32 UTC
Labels: declined: duplicate
