### ISSUE TITLE
Show mutual servers in friends list

### ISSUE THREAD

**Issue by imadtg** [powercord-community/suggestions#228] opened 2020-10-18 22:03 UTC
### Description
this was originally a feature in discord and for some reason it got removed and i know there's a BD plugin for this too. it essentially shows a list of mutual servers next to your friends' icons in the friend list.
### More info
since this was originally a feature and there's a BD plugin for that i think it'd be plausible.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment] 2020-10-18 22:03
Duplicate of #131

**Closed by Bowser65** 2020-10-18 22:03 UTC
Labels: pending review
