### ISSUE TITLE
Pin DMS

### ISSUE THREAD

**Issue by niksey07** [powercord-community/suggestions#517] opened 2021-07-10 19:28 UTC
### Description
Basically lets you make new categories where you can Pin DMs/GRoup Chats
Like this: https://i.imgur.com/5kYk8F3.png

### More info
Theres a version of this in BetterDiscord, but when using it with bdcompat its very buggy

----

 - [ ] I checked if this request wasn't already proposed
 - [ ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-07-10 19:49
Duplicate of #209

**Closed as completed by cyyynthia** 2021-07-10 19:49 UTC
Labels: declined: duplicate
