### ISSUE TITLE
Collapsible server list

### ISSUE THREAD

**Issue by John4167** [powercord-community/suggestions#149] opened 2020-08-15 18:10 UTC
**Describe the plugin**
A clear and concise description of what the plugin would do.
Click on a role on the server list to make the people in the role disappear on the server list.

**Expected behavior**
A clear and concise description of what you expect to happen.
Once a role name is clicked on the server list the people in the role should disappear from the list. Once clicked the role name again they should reappear. Once a role is collapsed it should make room for the next role. As shown here, https://media.discordapp.net/attachments/389049952732446733/713120936521498634/4z0VKtkLtyuo.gif?width=107&height=300
You can add other context, mockups or anything else here.
Originally introduced by Betterdiscord by Lighty but was abandoned.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment] 2020-08-15 18:21
Duplicate of #16

**Closed by Bowser65** 2020-08-15 18:21 UTC
Labels: pending review
