### ISSUE TITLE
Pinning DMs

### ISSUE THREAD

**Issue by Alfred-207** [powercord-community/suggestions#333] opened 2021-01-14 16:41 UTC
### Description
Pin DMs to the DM list.

### More info
See screenshot below, you can make categories and assign people to said categories.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

![](https://i.vgy.me/sBTT9D.png)

**Comment by BenSegal855** [comment] 2021-01-14 16:44
Duplicate of #209

**Closed as completed by BenSegal855** 2021-01-14 16:44 UTC
Labels: declined: duplicate
