### ISSUE TITLE
Favourite media plugin

### ISSUE THREAD

**Issue by thesakamata** [powercord-community/suggestions#637] opened 2021-10-24 22:08 UTC
### Description
A plugin similar to Favourite media that allows you to favourite videos, images and other things for using at later times.

### More info
The plugin is available on betterdiscord (but is impossible to use with bdcompat because 0pluginlibary crashloops)

----

 - [ x ] I checked if this request wasn't already proposed
 - [ x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by GooglyBlox** [comment] 2021-10-24 22:55
Not sure if I'm supposed to mention this, but I remember seeing this as [#535](https://github.com/powercord-community/suggestions/issues/535).

**Comment by cyyynthia** [comment] 2022-03-11 11:37
Duplicate of #535

**Closed as completed by cyyynthia** 2022-03-11 11:37 UTC
Labels: declined: duplicate
