### ISSUE TITLE
Changing compression algorithm for uploaded files

### ISSUE THREAD

**Issue by AugustusUKR** [powercord-community/suggestions#382] opened 2021-03-09 12:03 UTC
### Description
Change the compression on uploaded files

### More info
If you don't have nitro you can compress the file just a bit more so you can share that funny meme with your friends. If you are trying to send a screen shot but the quality just isn't good enough and you have some upload size head room, you can "remove some compression." I am sure there are many more examples etc and situations people will have where this is a great plugin for them to have.  

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-03-09 14:03
Duplicate of #101 

As for "removing the compression" you can't programatically make an image suddenly become better, compression is a lossy process and high quality data is *lost* in the process. It's a one-way processing.

**Closed as completed by cyyynthia** 2021-03-09 14:03 UTC
Labels: declined: duplicate
