### ISSUE TITLE
Collapsable Display Roles in Member List

### ISSUE THREAD

**Issue by uBreeze** [powercord-community/suggestions#490] opened 2021-06-17 10:22 UTC
### Description
Similarly to how you can close and open categories in a dropdown menu for channels, you should be able to close and open display roles for easier organization of your member list. I think it'd look pretty neat.

### More info
Nothing much for me to add. I think it'd just be pretty cool to see only "Online - 240" instead of the entire universe.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-06-17 10:26
Duplicate of #16

**Closed as completed by cyyynthia** 2021-06-17 10:26 UTC
Labels: declined: duplicate
