### ISSUE TITLE
Better Status

### ISSUE THREAD

**Issue by abUwUser** [powercord-community/suggestions#105] opened 2020-06-01 18:41 UTC
# Describe the plugin
The plugin adds a functionalities to the status' Discord feature like:
* Custom time to clear the custom status
* Temporary status
* Auto-set custom status when a specific game/program is opened
* Mobile indicator for when the user is using mobile and has a status that isn't offline (obviosly) and online

# Expected behavior
## Custom clear time
If it isn't possible to make it using Discord's API or something else (probally its impossible and if it is possible, it will against the Powercord TOS), so here is a workarround to that:
* First: When used the custom status clear time, it will set the clear time to "Don't clear", and will starts a internal count, waiting only for hitting the time set by the user.
* Second: When the counts gets to 0, the status will be clear and everything reseted.

## Temporary status
Mine workarround suggestion is simmilar to the Custom clear time: It starts a count and will return back to the previous status.

## Auto-set status when a specific game/program is opened
When a game or a program specified by the user is launched, it will change the status. And when closed, it will return to the previous status. This can work with custom status too.

## Mobile indicator for when the user is using mobile and has a status that isn't offline (obviosly) and online
When somebody is using discord on mobile and has the indicator as DnD or Idle, Desktop version doesn't shows the mobile indicator. But with this plugin, it will show.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment] 2020-06-01 18:45
Duplicate of #83, #81, #40

**Closed by Bowser65** 2020-06-01 18:45 UTC
Labels: pending review
