### ISSUE TITLE
Timestamp Typer

### ISSUE THREAD

**Issue by DracoClaw** [powercord-community/suggestions#523] opened 2021-07-13 15:58 UTC
### Description
A plugin that lets you easily insert a timestamp.

### More info
With the release of the Timestamps, it would be great to have the ability to easily select a date or time and have it automatically formatted into a timestamp to be put in chat. 

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-07-13 15:59
Duplicate of #507

**Closed as completed by cyyynthia** 2021-07-13 15:59 UTC
Labels: declined: duplicate
