### ISSUE TITLE
Plugin that can display all people with a certain role.

### ISSUE THREAD

**Issue by CallumUncensored** [powercord-community/suggestions#475] opened 2021-06-06 16:40 UTC
### Description
A plugin that can display every user with a certain role. For Example: .list (role). (Image below).
![DiscordCanary_RfERGLK6Pj](https://user-images.githubusercontent.com/45427259/120932447-af910e00-c6ed-11eb-8427-d821289be655.png)

### More info
Maybe an option to output IDs too? and maybe output to a file?
This might not be able to be done in some larger servers, so a limitation would be good for a roles with over 1000 people, maybe you could override this with settings, but I doubt this because this might be classed as API abuse if it gets too many people.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-06-21 12:48
Duplicate of #58

**Closed as completed by cyyynthia** 2021-06-21 12:48 UTC
Labels: declined: duplicate
