### ISSUE TITLE
User account popout 

### ISSUE THREAD

**Issue by BluCobalt** [powercord-community/suggestions#408] opened 2021-03-29 21:50 UTC
### Description
When clicking the user icon in the bottom left, the server user popout will show up. 

### More info
Like [AccountDetailsPlus](https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/AccountDetailsPlus), but for powercord.
*I can't get the existing AccountDetailsPlus to work with bdCompat

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment] 2021-03-29 22:34
Interesting idea. I had requested something similar as a feature for Guild Profile by @NurMarvin https://github.com/NurMarvin/guild-profile/issues/14

**Comment by sitiom** [comment] 2021-03-30 10:19
Duplicate of #400

**Closed as completed** 2021-03-30 13:51 UTC
Labels: declined: duplicate
