### ISSUE TITLE
Spell Check / Grammerly For Discord

### ISSUE THREAD

**Issue by Leizurly** [powercord-community/suggestions#552] opened 2021-08-02 01:15 UTC
### Description
It would edit the spelling or grammer of discord msgs as Grammerly would.

### More info
There could be a toggle to auto check before msgs are sent, or if it is manual like grammerly. May need to pull from grammerlys API if you want it exactly but there are other ways too.

----

 - [ X] I checked if this request wasn't already proposed
 - [ X] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-08-02 11:41
Duplicate of #262

**Closed as completed by cyyynthia** 2021-08-02 11:41 UTC
Labels: declined: duplicate
