### ISSUE TITLE
Port of DevilBro's "RemoveBlockedUsers"

### ISSUE THREAD

**Issue by TYTheBeast** [powercord-community/suggestions#529] opened 2021-07-21 19:45 UTC
### Description
A plugin which completely removes users you've blocked from ever appearing in your client. You don't hear them in voice channels, you don't see their messages, you don't even see them mentioned (If someone else mentions them, it appears as "Unknown User").
Here's the original plugin's settings
![image](https://user-images.githubusercontent.com/19373069/126548438-fd337a61-d8e3-4993-a5d6-cb0878236e4e.png)

### More info
I believe some or many of the people that use this plugin have it for the sole purpose of blocking out some of the nasty exceptions of Discord users, e.g., your friend's server may have a user which loves mayonnaise, but mayo makes you really uncomfortable.
The source for the original plugin can be found [here](https://github.com/mwittrien/BetterDiscordAddons/blob/8184663444cdb2043ffcdfabbb2c6b75aa03ef82/Plugins/RemoveBlockedMessages/RemoveBlockedMessages.plugin.js)
Please note that the reason why I'm making this request is because I've been told that DevilBro's library and plugins are not performance-efficient and cause a memory leak.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-07-21 20:09
Duplicate of #36

**Closed as completed by cyyynthia** 2021-07-21 20:09 UTC
Labels: declined: duplicate
