### ISSUE TITLE
Simple plugin that jumps to a new message while not in focus.

### ISSUE THREAD

**Issue by ryseprojects** [powercord-community/suggestions#326] opened 2021-01-08 23:12 UTC
### Description
A simple, toggleable plugin that opens a channel where you got a message without Discord in focus. For users with a secondary monitor.

### More info
The plugin will open a new message upon receival. Will not open the message if the user/channel is muted. Want this so I don't need to constantly alt-tab to discord and interrupt my game. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-01-10 14:27
Duplicate of #325

**Closed as completed by cyyynthia** 2021-01-10 14:27 UTC
Labels: declined: duplicate
