### ISSUE TITLE
Advanced Search - Search in all Servers & Dms

### ISSUE THREAD

**Issue by QDaves** [powercord-community/suggestions#526] opened 2021-07-18 23:36 UTC
### Description
A Plugin which will search in all servers not only in one, also a option search in all friend dms for specific stuff.
![image](https://user-images.githubusercontent.com/26190695/126085498-e360f75a-6f80-4f15-82ac-e8e403157d7e.png)

### More info
Maybe add option like search only in XY Servers you have choosen or all, same for dms.
This would very usefull for alot of people.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment] 2021-07-18 23:44
Duplicate of #156

**Closed as completed by BenSegal855** 2021-07-18 23:44 UTC
Labels: declined: duplicate
