### ISSUE TITLE
Twemoji everywhere

### ISSUE THREAD

**Issue by Mara-Li** [powercord-community/suggestions#359] opened 2021-02-15 09:15 UTC
### Description
A plugin who replace **all emoji** used by discord by twemoji.

### More info
Okay, so, we have a plugin to change **the emoji** in **chat**, but not a plugin to change / update emoji used around discord : channel name, nickname, and also custom status texte.

Actually, on windows, Emoji in channel name looks like this : 
![image](https://user-images.githubusercontent.com/30244939/107926308-d88e6700-6f75-11eb-950c-fd6da6abfe5f.png)
Yeah, I know, it's bad.

My request is, simply, change the emoji to twemoji. A old plugin on Better Discord exist and work (for the moment). You can find [here](https://github.com/micelle/BetterDiscordPlugins/blob/master/plugins/Twemoji.plugin.js). Unfortunately, it doesn't work with the BD adaptator. Maybe it's because of the new electron update, or it's just a normal incompatibility.

After check with the plugin and on normal discord (with BD and the plugin) : 
![image](https://user-images.githubusercontent.com/30244939/107926754-5e121700-6f76-11eb-9f09-8f4cf70171d7.png)

And on Canary : 
![image](https://user-images.githubusercontent.com/30244939/107926959-a5000c80-6f76-11eb-8988-7f2ad2620a70.png)

I really don't know how I can change that because I really know nothing about plugins and the language used here (I know only python) so I hope all information gived here can help someone to create something ! 

----

 - [x ] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-02-15 09:28
Duplicate of #200 - Although it only mentions the channels, you should comment on this issue instead

**Closed as completed by cyyynthia** 2021-02-15 09:28 UTC
Labels: declined: duplicate
