### ISSUE TITLE
foobar2000 modal like spotify's

### ISSUE THREAD

**Issue by absxl** [powercord-community/suggestions#229] opened 2020-10-19 21:30 UTC
### Description
foobar2000 modal like spotify's one that is natively delivered with powercord

### More info
Litterally that, pause, skip, seekbar, etc. like spotify modals in the spotify plugin but it works with foobar2000

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment] 2020-10-19 21:47
Duplicate of #129

**Closed by Bowser65** 2020-10-19 21:47 UTC
Labels: pending review
