### ISSUE TITLE
Pin DMs or Channels to Top of List

### ISSUE THREAD

**Issue by KorbsStudio** [powercord-community/suggestions#271] opened 2020-11-18 08:25 UTC
### Description
Pin channels in servers

### More info
Pin icon should be put next to Create Invite button on channel names.

Would be nice to have this has I answer tickets on a server, there are tons of them, and I sometimes loose the ones I need to come back to.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by MulverineX** [comment] 2020-11-20 17:07
[This](https://github.com/A-Trash-Coder/Quick-Channel-Mute) would provide the list channel item injection.

Also, I would suggest, as I did to quick channel mute, that there be an optional keybind for showing the button, as the list can get pretty cluttered with multiple buttons all the time.

**Comment by TheShadowGamer** [comment] 2020-12-01 16:20
Isn’t this a duplicate of #209? Or am I missing something? Couldn’t pinned channels just be added to that one?

**Comment by MulverineX** [comment] 2020-12-01 16:48
#209 shouldn't be up anymore imo, group DM support should be in betterfriends. But yes *this* issue should be scoped to just server channels, not sure if it should be moved to betterfriends as well.

**Comment by Jirubizu** [comment] 2021-04-13 15:44
I too would like something like this. Moderating large servers becomes horrible with many channels. having a pinned section of channels to look at would be super useful.

**Comment by ghost** [comment] 2021-04-19 21:21
Nowadays I kinda just rename a ticket channel from something like `000-ticket` to `000-ticket-korbs`.
But seeing this plugin developed for other users would be very nice and helpful for those moderators.
Even tho I no longer use Powercord or mod Discord in general.

**Comment by MulverineX** [comment] 2021-04-20 03:24
@KorbsStudio DM pinning already exists https://github.com/powercord-community/betterfriends

**Comment by ghost** [comment] 2021-04-20 05:07
We know, but I'm mainly focused on pinning channels as well, which is a higher priority for me.

**Comment by ghost** [comment] 2021-07-05 21:49
https://www.reddit.com/r/discordapp/comments/oe57a5/discord_pinned_chat_in_dms_design_concept/

Concept created by u/AlexKF0811 and posted on Discord's reddit.

**Comment by MulverineX** [comment] 2021-07-05 22:09
Why? Again that already exists. If you think that betterfriends' UI should change to be closer to that then file an Issue on it's repository

**Comment by ghost** [comment] 2021-07-06 01:22
No, I'm still wanting to pin channels.

**Comment by MulverineX** [comment] 2021-07-06 01:57
That reddit post is irrelevant then

**Comment by ghost** [comment] 2021-07-07 15:21
The concept of what the Reddit post is a good idea, so the same should be done with channels.
If the developer of BetterFriends wants to do it, then let them.

**Closed** 2021-10-22 03:14 UTC
Labels: up for grabs
