### ISSUE TITLE
A clock  inside discord with the ability to add clocks set to different time zones on peoples profiles.

### ISSUE THREAD

**Issue by sircheezball** [powercord-community/suggestions#247] opened 2020-10-31 14:34 UTC
### Description
You can add a clock inside discord set to your timezone. But you can also make it so when you click on someones profile you will see a clock set to their time zone. Possibly with the ability for other powercord users using that plugin to see the clock on your profile if you want it.
### More info
 
----

 - [x ] I checked if this request wasn't already proposed
 - [ x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DanKGooGLy** [comment] 2020-10-31 15:03
I believe this was already proposed.

**Comment by taikutsunan** [comment] 2020-11-01 23:01
this was indeed already proposed in #185

**Comment by Bowser65** [comment] 2020-11-02 09:24
Duplicate of #185

**Closed by Bowser65** 2020-11-02 09:24 UTC
Labels: pending review
