### ISSUE TITLE
collapsible member grouping

### ISSUE THREAD

**Issue by doggybootsy** [powercord-community/suggestions#388] opened 2021-03-16 05:02 UTC
### Description
makes the member group act like channels with the ability to collapse 

### More info
Before: https://i.imgur.com/LvqYPVV.png
After: https://i.imgur.com/6ZXRsci.png

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by GriefMoDz** [comment] 2021-03-16 05:08
Duplicate of #16

**Closed as completed by GriefMoDz** 2021-03-16 05:08 UTC
Labels: declined: duplicate

**Comment by doggybootsy** [comment] 2021-03-16 05:09
oh thx
