### ISSUE TITLE
Blocked words/phrases

### ISSUE THREAD

**Issue by Tangytube** [powercord-community/suggestions#212] opened 2020-10-02 09:12 UTC
### Description
A plugin which would add a blocked words list for words you dont want to see.

### More info
There would be a menu where you can add words or phrases to a list, and an option to either make the word censor (example: if you censored 'fuck' it would show up as 'f**k'), show up as "1 muted message" (mock-up attached) or just make the message not show up altogether.
![image](https://user-images.githubusercontent.com/71666730/94907065-96a0d080-046d-11eb-8802-2d31b8eeb43d.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment] 2020-10-02 09:16
Duplicate of #122; Though it might be worth posting the mockup there as it's looking nice

**Closed by Bowser65** 2020-10-02 09:16 UTC
Labels: pending review
