### ISSUE TITLE
Exclude from search

### ISSUE THREAD

**Issue by SirHaxe** [powercord-community/suggestions#203] opened 2020-09-25 16:49 UTC
### Description
a way to exclude things from search

### More info
example: Powercord !in:#off-topic to search in every channel except off topic

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by oatmealine** [comment] 2020-09-25 18:18
wouldnt you need to modify the serverside for this to work? the search is an api, and i heavily doubt it has support for that
if you were to use this to filter out results, there would often be inconsistent page numbers and its overall not a very good idea

**Comment by Bowser65** [comment] 2020-09-25 18:20
You can emulate such behavior by including all channels via `in:` except the ones you don't want

**Comment by MulverineX** [comment] 2020-09-25 20:58
Another nice thing to have would be a `category:` parameter to search all channels within a category. (using the same technique of including all channels via `in:`)

**Comment by MulverineX** [comment] 2020-09-25 21:00
And if you're making a search utility plugin, may as well do the generic thing of adding (easier) pagination a-la BetterSearch from BD.

**Comment by Bowser65** [comment] 2020-09-26 07:20
Those two additions have already been requested in #23 #156

**Comment by Bowser65** [comment] 2020-09-26 18:50
After some discussion (& some issue updating), I'll mark this as duplicate of #156

**Closed by Bowser65** 2020-09-26 18:50 UTC
Labels: up for grabs
