### ISSUE TITLE
(Library) Client Side Simulated Servers

### ISSUE THREAD

**Issue by Hexcede** [powercord-community/suggestions#100] opened 2020-05-19 12:38 UTC
**Describe the plugin**
A (barebones) library which can simulate basic functionality of a Discord server in the client (for integrations with other sites/services) allowing a developer to display content like a Discord server would (most likely through limited API request proxying).

**Expected behavior**
The library can display an empty server with a name and icon (no users other than the client user), can display text channels, categories, etc through an API (I don't think voice channels would really be useful), can supply an interface for handling messages sent by the user as well as display responses from our friend Clyde (alternatives) and (potentially?) users with their own name and icon although I'd prefer them to appear like webhooks with a Bot tag to mitigate malicious usage.

Lastly, I'd expect no API communication from the client to Discord for the locally simulated server as it wouldn't be a real server (it would be bad if the library spams Discord APIs with completely invalid content). The more actual functionality able to be displayed/handled through the library (e.g. server settings, users in the sidebar, role editing), the better, but I'd not expect many of Discord's features to be easy to work with, nor would I expect them to be future proof, nor would I expect blocking API calls to be easy.

I don't know how possible this idea is, and I don't know how future proof this idea could be, so if this sounds like it wouldn't be plausible to last or sounds like it would be a huge pain to implement, I don't see it becoming a thing. My intentions are to be able to use this to integrate with other sites/services.

Some examples of what I think this could be used for/stuff I'd want to use this for:
Integration with a Discord Bot to simulate control of the bot, integration with sites with similar usage to Discord such as Slack or various chat services, integration with github such as displaying issues, commits, etc in a unified place.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by NurMarvin** [comment] 2020-05-19 13:02
This is definitely possible but it's quite a lot of work.
I'm currently working on Discord Backend API clone for bot unit testing and stuff and it took me an entire day to just implement the basic guild functionality. Besides that, hooking into the right things in the client will also be quite hard to figure out, especially when you need to hook into so many things to prevent any API requests to Discord.
So yes, it would be possible, I'm just not 100% sure how complicated it would be.

**Comment by Hexcede** [comment] 2020-05-19 13:30
> This is definitely possible but it's quite a lot of work.
> I'm currently working on Discord Backend API clone for bot unit testing and stuff and it took me an entire day to just implement the basic guild functionality. Besides that, hooking into the right things in the client will also be quite hard to figure out, especially when you need to hook into so many things to prevent any API requests to Discord.
> So yes, it would be possible, I'm just not 100% sure how complicated it would be.

Yeah, I'd assumed it would be possible, but probably an enormous pain. I have no clue how feasible it'd be to implement, and I pretty much already know it's going to be an enormous pain to maintain over a long period of time. I like doing that kind of stuff myself, and maintaining mods like this just because it's something complex I can exercise myself on, but I've only just gotten into how Discord, Powercord, etc work, and I'm still getting familiar with what is an absolute pain and what isn't an absolute pain besides what experience I have with web client modding.

Discord modding (at least in regards to plugins) reminds me a lot of Screeps client modding so far. The Screeps client uses angular and a client similar to electron, which, from what I've gotten so far, modding angular code works pretty similarly to here where you're essentially searching for modules that have the specific APIs you want, except in angular you'd have to take it one step further and locate which specific elements the module is defined under, and if that module changes at all, or moves, you've gotta change what you're searching for all over again, and if that module is completely removed, you've gotta figure out how to do what you want to do from the beginning.

**Comment by Bowser65** [comment] 2020-05-20 23:27
The problem is that a LOT of Discord internals pretty much rely on "if resource X not found then Request API" which makes doing those kind of injections extremely difficult. Not to mention any change, even the slightest in Discord's internal state management or in the format the data is received could break the plugin.

Unless you have tons of time to waste you're better of making your own re-impl of the front design if you want to display content in a discord-like way w/o API communications

**Comment by CodingKanin** [comment] 2020-08-29 05:19
So what's the verdict on this?

**Comment by Bowser65** [comment] 2020-08-29 09:54
I'll close this due to technical constraints. The amount of work for this kind of stuff is way too large, and you can just register a new route using Powercord's router API and then build the UI yourself based on Discord components.

Making it as "Fake servers" might sound like a good idea but in fact it just causes way too much pain and injections, especially to prevent Discord from making API calls in those specific places. Just rebuilding the UI yourself should be easy and relatively straightforward, just grab the React component tree via React DevTools (standalone or in a web browser) and recreate the tree by yourself.

**Closed by Bowser65** 2020-08-29 09:54 UTC
Labels: pending review
