### ISSUE TITLE
Vim  Keybinds 

### ISSUE THREAD

**Issue by ghost** [powercord-community/suggestions#432] opened 2021-05-08 17:53 UTC
### Description
A clear and concise description of what the plugin would do.
Don't get too specific, that's for the next part.

A plugin that would implement the Vim keybindings (i.e. J to go down, H to go up, H to go left, L to go right ((H & L would be used for sending messages, and by pressing insert or I (((via maybe XYZ (Key set by the user + XYZ key you could move when already typing in the discord chat))) )) 

maybe gT and gt to move servers and so on.

### More info
You can here put more technical information, or get more specific.
Feel free to also add context, mockups or anything else here.

Maybe taking a look @ the Vimium source code (https://github.com/philc/vimium) would help since its written in JS

It's basically vim keys but in the web browser (Firefox & Chromium  compatible) 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-06-02 17:57
There is already a request about a plugin to enhance keybind settings that could cover this request. I'll consider this a duplicate of #116

**Closed as completed by cyyynthia** 2021-06-02 17:57 UTC
Labels: declined: duplicate
