### ISSUE TITLE
EditUploads port

### ISSUE THREAD

**Issue by SandeMC** [powercord-community/suggestions#422] opened 2021-04-19 13:12 UTC
### Description
Edit uploads before sending them.

### More info
![image](https://user-images.githubusercontent.com/70141395/115241790-e012ed80-a129-11eb-94bd-ec7d8ab56bfe.png)
![image](https://user-images.githubusercontent.com/70141395/115241828-eb661900-a129-11eb-9886-f632ecbab311.png)
![image](https://user-images.githubusercontent.com/70141395/115241844-ef923680-a129-11eb-8c5d-8d4aea06704d.png)
![image](https://user-images.githubusercontent.com/70141395/115241866-f751db00-a129-11eb-9392-7a2dfb595092.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-04-19 13:46
Duplicate of #157

**Closed as completed by cyyynthia** 2021-04-19 13:46 UTC
Labels: declined: duplicate
