### ISSUE TITLE
Message Keyboard Navigator

### ISSUE THREAD

**Issue by PWalll** [powercord-community/suggestions#282] opened 2020-11-25 00:33 UTC
### Description
Navigate the messages on the channel you are currently in with the keyboard.

### More info
Navigating through the message history of the channel you are in rightnow selecting it one by one been able to go up by one with a keybinding (like super + w) and go down one message with another keybinding (like super + s), also been able to select text on the currently selected message with something like (shift + a or shift + d).

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by PWalll** [comment] 2020-11-25 00:47
It would be also nice if to add things like editting it if is yours, delete it, reacting and replying...

**Comment by Bowser65** [comment] 2020-11-25 14:44
Duplicate of #116

**Closed by Bowser65** 2020-11-25 14:44 UTC
Labels: pending review
