### ISSUE TITLE
Gif Saver

### ISSUE THREAD

**Issue by zzerexx** [powercord-community/suggestions#448] opened 2021-05-18 12:36 UTC
### Description
Saves favorited gifs into a folder.

### More info
Basically this [plugin](https://github.com/bepvte/bd-addons/blob/main/plugins/gifsaver.plugin.js) but for Powercord.
It saves all your favorited gifs into a folder and restores them when Discord erases them.
Kind of annoying to see all your favorited gifs disappear after you've logged back into your account.
(yes this has been requested already but it would be really helpful to have)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Vendicated** [comment] 2021-05-18 12:48
duplicate of #252  but definitely a cool idea! I might make this soon™

**Comment by BenSegal855** [comment] 2021-05-18 14:10
As you stated, this is a duplicate of #252.

**Closed as completed by BenSegal855** 2021-05-18 14:10 UTC
Labels: declined: duplicate
