### ISSUE TITLE
Move Custom CSS

### ISSUE THREAD

**Issue by jeffboy70** [powercord-community/suggestions#180] opened 2020-09-10 00:23 UTC
### Description
Just moves the Custom CSS tab in Themes to its own section in settings

### More info
The tab would probably be above Themes.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment] 2020-09-10 12:53
Duplicate of #133

**Closed by Bowser65** 2020-09-10 12:53 UTC
Labels: pending review
