### ISSUE TITLE
Multiple images per message

### ISSUE THREAD

**Issue by Vresod** [powercord-community/suggestions#434] opened 2021-05-09 16:26 UTC
### Description
Allow uploading multiple images per message, like you can on mobile.

### More info
Could potentially replace or add on to the situation in which you have the "Cancel all" button when uploading images, ie
![image](https://user-images.githubusercontent.com/40863375/117579604-afd3c480-b0c1-11eb-9c54-98dc054b8b10.png)

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-05-09 16:29
Duplicate of #243

**Closed as completed by cyyynthia** 2021-05-09 16:29 UTC
Labels: declined: duplicate
