### ISSUE TITLE
Plugin similar to FavoriteMedia

### ISSUE THREAD

**Issue by ypurpl** [powercord-community/suggestions#706] opened 2022-03-11 00:49 UTC
### Description
Just like the FavoriteMedia plugin from BD that allows you to favorite more than just gifs, such as videos, images or even audio files.
### More info
Here's the actual [plugin](https://betterdiscord.app/plugin/FavoriteMedia) if you want to see it in action

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2022-03-11 11:37
Duplicate of #535 #637

**Closed as completed by cyyynthia** 2022-03-11 11:37 UTC
Labels: declined: duplicate, pending review
