### ISSUE TITLE
Image zoom utility 

### ISSUE THREAD

**Issue by Ezgon** [powercord-community/suggestions#233] opened 2020-10-21 21:32 UTC
### Description
A -lightweight- image zoom like 1lighty BetterDiscord one

### More info
The reason I won't one made for powercord is that BDcompat have very bad performance and it requires 2 library's to run

----
 - [ X ] I checked if this request wasn't already proposed
 - [ X ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment] 2020-10-21 22:07
Duplicate of #155

**Comment by MulverineX** [comment] 2020-10-23 22:14
@Ezgon ^^^, please close this issue. Also a tip: spaces don't go around the x in a checkbox.

**Comment by Bowser65** [comment] 2020-10-24 17:41
Duplicate of #155

**Closed by Bowser65** 2020-10-24 17:41 UTC
Labels: pending review
