### ISSUE TITLE
Rauf embed generator

### ISSUE THREAD

**Issue by DerpoDrago** [powercord-community/suggestions#275] opened 2020-11-20 04:50 UTC
### Description
A command (e.g. .embed) that takes arguments and creates an embedded message from this site -> https://test.rauf.workers.dev/

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Sidemen19** [comment] 2020-11-20 04:59
Yes, I suggested [Safe Embed Generator](https://github.com/Controlfreak707/safe-embed-generator) to use this site as it doesn't require an API request, making it faster. That suggestion didn't go anywhere. Anyhow, this suggestion is a duplicate of the aforementioned plugin, and a command could probably be implemented in to it if you leave an issue on its repo.

**Comment by Bowser65** [comment] 2020-11-20 12:56
This'd be better suited as a request for the already existing plugin as per [guideline 11](https://powercord.dev/guidelines#11-prefer-contributing-instead-of-duplicating). You should open an issue on their repo instead.

**Closed by Bowser65** 2020-11-20 12:56 UTC
Labels: pending review
