### ISSUE TITLE
Hide Voice Channels

### ISSUE THREAD

**Issue by DracoClaw** [powercord-community/suggestions#150] opened 2020-08-15 23:14 UTC
### Description
A way to hide voice channels the same as text channels.

### More info
For text channels you can mute them and then hide muted channels, but that is not the case for voice channels. Id love a way to hide them completely, the same as text ones. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment] 2020-08-15 23:18
Wouldn't this be a duplicate of #19?

**Comment by botatooo** [comment] 2020-08-15 23:20
> Wouldn't this be a duplicate of #19?

y e s   i t   i n d e e d   i s

**Comment by DracoClaw** [comment] 2020-08-15 23:24
oh i guess it is. didnt see that as its fairly old, also it does not mention voice channels.

**Comment by Bowser65** [comment] 2020-08-16 00:33
Yeah, might be worth commenting on this issue rather than opening a new one

**Closed by Bowser65** 2020-08-16 00:33 UTC
Labels: pending review
