### ISSUE TITLE
Voice Change Plugin

### ISSUE THREAD

**Issue by ghost** [powercord-community/suggestions#464] opened 2021-06-02 15:07 UTC
### Description
A Plugin to voice change on a Discord Call

### More info
To make my voice funny, loud or deep.

----

 - [ x ] I checked if this request wasn't already proposed
 - [ x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by onixiya1337** [comment] 2021-06-20 20:57
Just use external software made for this.

**Comment by MulverineX** [comment] 2021-06-21 00:11
@onixiya1337 a lot of those suck and/or are paid

**Comment by katlyn** [comment] 2021-07-29 05:16
Duplicate of #195

**Closed as completed by katlyn** 2021-07-29 05:16 UTC
Labels: declined: duplicate
