### ISSUE TITLE
Search Sort

### ISSUE THREAD

**Issue by ghost** [powercord-community/suggestions#401] opened 2021-03-27 20:41 UTC
### Description
A plugin that lets you sort messages from the most reacted messages to the least, or the longest message and the shortest
in the server when you search for something.

----
 - [ ] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-03-28 15:19
First off it'd fall as a duplicate of #156, and then you can't use these sorting methods because those aren't supported by Discord's API which is the only component responsible for sorting search results. While you could technically do it, all of the methods that could be used would be in violation of our guidelines for doing a lot of requests to the Discord API.

**Closed as completed by cyyynthia** 2021-03-28 15:19 UTC
Labels: declined: technical constraints
