### ISSUE TITLE
Grammar Corrector / Auto Correct messages

### ISSUE THREAD

**Issue by NotTaze** [powercord-community/suggestions#459] opened 2021-05-24 04:52 UTC
### Description
A plugin that corrects/auto corrects your grammer before you send a message. 

### More info
A plugin that auto correct messages or a plugin like grammarly/grammer corrector. Since on discord, a lot of people misspell words, this would be great for the powercord community and for discord in general.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment] 2021-05-24 13:03
Duplicate of #262

**Closed as completed by cyyynthia** 2021-05-24 13:03 UTC
Labels: declined: duplicate
