### ISSUE TITLE
Ability to Hide Channels

### ISSUE THREAD

**Issue by Renaitare** [powercord-community/suggestions#87] opened 2020-03-28 13:11 UTC
**Describe the plugin**
At the moment you can only hide muted channels and that too it's a server-wide thing within the Discord client. I would like the ability to be able to just hide channels regardless of whether they are muted or not (more explanation in expected behavior.

**Expected behavior**
Add a simple action in the right-click context menu that allows the user to hide the channel at will. If the channel isn't muted, it should reappear if there are unread messages on it. If it is muted, it will stay hidden until the user decides to visit the channel. They should be able to see muted channels either in settings or view them in some sort of menu in the server/guild dropdown. 

You can add other context, mockups or anything else here.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Juby210** [comment] 2020-03-28 13:16
duplicate of #19

**Closed** 2020-03-30 08:36 UTC
Labels: duplicate
