### ISSUE TITLE
Open links in discord's electron browser

### ISSUE THREAD

**Issue by MIHAIdavid22** [powercord-community/suggestions#251] opened 2020-11-02 17:22 UTC
### Description
Opens links,images,videos inside discord's own browser
### More info

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Bowser65** [comment] 2020-11-02 17:26
Duplicate of #80

**Closed by Bowser65** 2020-11-02 17:26 UTC
Labels: pending review
